name: DV Regression
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Install Icarus
        run: sudo apt-get update && sudo apt-get install -y iverilog
      - name: Run regression
        run: make regress
